runs:
    using: composite
    steps:
      - id: install-display-system
        name: Install display
        run: sudo apt install -y xvfb x11-utils libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0 xdotool
        shell: bash

      - id: install-pipenv
        name: Install pipenv
        run: pipx install pipenv
        shell: bash

      - id: install-python
        name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pipenv'

      - id: install-python-dependencies
        name: Install Python dependencies
        run: |
          pipenv install --dev
          pipenv run pip install certifi
        shell: bash
